version: "3.8"
services:
  mongodb:
    image: mongo:5.0.15
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USER=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
# docker compose -p mongodb-data up -d
